notifications:
  webhooks:
    - urls:
      - secure: "hNLYkSLonZ6OX8UleFH8hdhFMTc1XAYB29oMLRgU9i4h8DS9YBn4Hj+RUZNla2ADKt3jzesauzFZNQaZjhFdooOpT3pZ6fcULp1wOKIZrxSr/7am3y2dR8EfWRl+6/m//t59RWHq+oNp+iMcuqoXn4W2QDkQ8u8ukau6oejJkO0ri6uuSetAuwBZmYfOpQTdEpwdjsvabRUFDjbzJBktKnRARNWGITRP2rciofxV8Z4PxLdBChDsbyz89RLTsvGYYihg/l52K3rN0oFIbPDue9ImE0CgoibC39zBkAKpRoea6h92X6zLGgZ4bn7aFTkvCxDMAi0JO/HOlurxLN1V4E6oYa0ix4S/XjEbuQPCluTLIqoCIgivhDKOeM+ZteXp6jUnvEwo+4aNJuc21f4nn0ZHJ4PDZ5mAQGp3TnueEp/rODFnARkmkhkchq2jaTKT/MB4IKlnDua0O5LwlGisX8RkXzQkzTKNHHvFWpQZo2XiPTdxLY5IV7Man6i1AlEXUckMrHWys9HDIboOl1jEVXyZtJIzVYhaghE6e5jNGItZExjAxXi8brKgBy40jnoDBZWZkmwt9SN9vR7nbn37djwiP9r1ZgqwnkBZFKkbzluFVSZ8sjFGDXwOHWVAJmVFs7U94iW/DJ6ND2t9Le/illQb9OLkKB8EbmUB4KXiTME="
    - on_start: always
    - on_cancel: always
    - on_error: always
    - on_success: always
    - on_failure: always
    - enabled: true

language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: beta
    - rust: nightly
    - arch: ppc64le
    - arch: s390x
  fast_finish: true
cache: cargo
compiler:
  - clang
  - gcc

os:
  - linux
  - windows
  - osx
dist:
  xenial
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x